services:
  - type: web
    name: movie-recommender-api
    env: python
    region: oregon
    rootDir: backend
    buildCommand: |
      pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: HUGGINGFACE_DATASET_REPO
        sync: false
      - key: FRONTEND_URL
        sync: false
