"""
Vibe — Dimension Keywords Module

Standalone module containing the DIMENSION_KEYWORDS lookup dictionary and
VIBE_PRESETS list. Imported by both seed_vibes.py (offline) and api.py (runtime).

6 atmosphere dimensions, each scored 0.0–1.0:
  lighting      0 = dark/noir         1 = bright/sun-drenched
  pacing        0 = slow/meditative   1 = kinetic/frenetic
  setting_type  0 = isolated/rural    1 = dense urban/crowded
  temperature   0 = cold/sterile      1 = warm/sultry/sun-baked
  texture       0 = raw/gritty        1 = polished/elegant
  era_feel      0 = vintage/period    1 = modern/futuristic
"""

# ── Six atmosphere dimensions ─────────────────────────────────────────────────

DIMENSIONS = ["lighting", "pacing", "setting_type", "temperature", "texture", "era_feel"]

# ── Keyword → dimension score lookup ─────────────────────────────────────────

DIMENSION_KEYWORDS: dict[str, dict[str, float]] = {
    "lighting": {
        "dark": 0.05,
        "noir": 0.08,
        "shadowy": 0.10,
        "dim": 0.15,
        "murky": 0.12,
        "moody": 0.20,
        "moody lighting": 0.20,
        "neon": 0.25,
        "overcast": 0.30,
        "grey": 0.28,
        "gray": 0.28,
        "misty": 0.22,
        "foggy": 0.20,
        "dusk": 0.35,
        "golden hour": 0.75,
        "sunlit": 0.88,
        "bright": 0.90,
        "sun-drenched": 0.95,
        "sunny": 0.92,
        "clinical": 0.85,
        "fluorescent": 0.80,
        "well-lit": 0.85,
        "luminous": 0.82,
        "glowing": 0.70,
        "radiant": 0.88,
        "bleached": 0.80,
        "washed out": 0.75,
        "candlelit": 0.38,
        "firelit": 0.42,
        "torch": 0.32,
        "moonlit": 0.28,
        "neon-lit": 0.25,
        "electric": 0.30,
        "backlit": 0.60,
        "overexposed": 0.82,
        "atmospheric": 0.25,
    },
    "pacing": {
        "slow burn": 0.05,
        "slow": 0.08,
        "meditative": 0.08,
        "contemplative": 0.10,
        "deliberate": 0.20,
        "languid": 0.15,
        "measured": 0.30,
        "quiet": 0.18,
        "minimalist": 0.12,
        "subtle": 0.22,
        "unhurried": 0.15,
        "brooding": 0.18,
        "methodical": 0.25,
        "moderate": 0.50,
        "tense": 0.75,
        "suspenseful": 0.70,
        "gripping": 0.72,
        "exciting": 0.78,
        "thrilling": 0.82,
        "fast-paced": 0.80,
        "fast": 0.82,
        "kinetic": 0.88,
        "frenetic": 0.92,
        "relentless": 0.90,
        "action-packed": 0.95,
        "explosive": 0.90,
        "breathless": 0.88,
        "propulsive": 0.85,
        "energetic": 0.80,
        "urgent": 0.78,
        "chaotic": 0.88,
        "frantic": 0.90,
        "intense": 0.80,
        "edge-of-your-seat": 0.88,
    },
    "setting_type": {
        "isolated": 0.05,
        "remote": 0.08,
        "wilderness": 0.10,
        "rural": 0.15,
        "countryside": 0.18,
        "forest": 0.12,
        "mountains": 0.15,
        "cabin": 0.10,
        "desert": 0.08,
        "ocean": 0.20,
        "coastal": 0.25,
        "island": 0.18,
        "small town": 0.25,
        "village": 0.22,
        "suburb": 0.45,
        "suburban": 0.45,
        "town": 0.40,
        "city": 0.75,
        "urban": 0.80,
        "metropolitan": 0.85,
        "crowded": 0.90,
        "cityscape": 0.88,
        "downtown": 0.85,
        "streets": 0.80,
        "alley": 0.75,
        "rooftop": 0.78,
        "skyscraper": 0.88,
        "apartment": 0.72,
        "industrial": 0.75,
        "warehouse": 0.70,
        "office": 0.80,
        "corporate": 0.82,
        "nightclub": 0.85,
        "underground": 0.72,
        "underground city": 0.82,
        "space": 0.30,
        "spaceship": 0.35,
        "futuristic city": 0.90,
    },
    "temperature": {
        "frozen": 0.03,
        "arctic": 0.05,
        "cold": 0.05,
        "wintry": 0.08,
        "winter": 0.10,
        "snow": 0.12,
        "icy": 0.08,
        "sterile": 0.10,
        "clinical": 0.12,
        "grey": 0.20,
        "cool": 0.30,
        "crisp": 0.35,
        "mild": 0.50,
        "neutral": 0.50,
        "autumn": 0.45,
        "fall": 0.45,
        "spring": 0.55,
        "warm": 0.72,
        "cozy": 0.75,
        "lush": 0.72,
        "humid": 0.80,
        "sultry": 0.85,
        "summery": 0.82,
        "summer": 0.80,
        "hot": 0.88,
        "sun-baked": 0.92,
        "mediterranean": 0.90,
        "tropical": 0.95,
        "sweltering": 0.92,
        "hazy": 0.78,
        "dusty": 0.75,
        "arid": 0.80,
        "scorching": 0.92,
        "firelit": 0.68,
        "candlelit": 0.65,
        "golden": 0.80,
        "amber": 0.78,
        "rainy": 0.25,
        "monsoon": 0.22,
        "drizzle": 0.28,
        "damp": 0.22,
        "wet": 0.20,
        "fog": 0.22,
        "mist": 0.25,
    },
    "texture": {
        "raw": 0.05,
        "gritty": 0.08,
        "handheld": 0.10,
        "rough": 0.12,
        "documentary-style": 0.15,
        "documentary": 0.15,
        "naturalistic": 0.25,
        "realistic": 0.40,
        "lo-fi": 0.15,
        "grainy": 0.12,
        "washed": 0.22,
        "unpolished": 0.18,
        "authentic": 0.35,
        "raw footage": 0.08,
        "found footage": 0.10,
        "verité": 0.12,
        "impressionistic": 0.45,
        "dreamy": 0.52,
        "stylized": 0.65,
        "cinematic": 0.72,
        "visual": 0.68,
        "visually stunning": 0.85,
        "gorgeous": 0.88,
        "lush": 0.80,
        "polished": 0.82,
        "glossy": 0.88,
        "slick": 0.85,
        "elegant": 0.90,
        "pristine": 0.92,
        "sleek": 0.88,
        "beautiful": 0.80,
        "lavish": 0.88,
        "opulent": 0.90,
        "sumptuous": 0.88,
        "epic": 0.75,
        "grand": 0.78,
        "sweeping": 0.80,
        "breathtaking": 0.85,
        "surreal": 0.55,
        "abstract": 0.48,
        "expressionist": 0.50,
        "minimalist": 0.40,
    },
    "era_feel": {
        "period piece": 0.05,
        "historical": 0.08,
        "ancient": 0.05,
        "medieval": 0.08,
        "victorian": 0.10,
        "vintage": 0.12,
        "classical": 0.12,
        "old": 0.15,
        "antique": 0.10,
        "retro": 0.18,
        "1920s": 0.12,
        "1930s": 0.13,
        "1940s": 0.14,
        "1950s": 0.16,
        "1960s": 0.20,
        "1970s": 0.24,
        "1980s": 0.28,
        "80s": 0.28,
        "nostalgic": 0.25,
        "timeless": 0.45,
        "classic": 0.38,
        "contemporary": 0.72,
        "modern": 0.80,
        "present day": 0.78,
        "2000s": 0.72,
        "2010s": 0.78,
        "current": 0.80,
        "near future": 0.85,
        "futuristic": 0.88,
        "sci-fi": 0.85,
        "science fiction": 0.85,
        "future": 0.88,
        "cyberpunk": 0.92,
        "dystopian": 0.88,
        "post-apocalyptic": 0.85,
        "space age": 0.90,
        "high-tech": 0.88,
        "digital": 0.82,
        "neon future": 0.92,
    },
}

# ── Flat reverse lookup: token → {dimension: score} ──────────────────────────

def build_flat_lookup(keyword_map: dict) -> dict:
    """Build a flat lookup: token → list of (dimension, score) for fast matching."""
    flat: dict[str, list] = {}
    for dim, keywords in keyword_map.items():
        for kw, score in keywords.items():
            for token in kw.lower().split():
                if token not in flat:
                    flat[token] = []
                flat[token].append((dim, score))
    return flat


FLAT_LOOKUP = build_flat_lookup(DIMENSION_KEYWORDS)

# ── 24 Vibe presets ───────────────────────────────────────────────────────────

VIBE_PRESETS = [
    {
        "id": "rainy-city-night",
        "display_name": "Rainy city night",
        "emoji": "🌧️",
        "description": "neon reflections, wet streets, 3am loneliness",
        "vector": [0.15, 0.22, 0.82, 0.18, 0.58, 0.72],
    },
    {
        "id": "dusty-road-trip",
        "display_name": "Dusty road trip",
        "emoji": "🛣️",
        "description": "open highway, warm summer, nostalgic freedom",
        "vector": [0.85, 0.52, 0.28, 0.88, 0.45, 0.32],
    },
    {
        "id": "cold-corporate",
        "display_name": "Cold corporate thriller",
        "emoji": "🏢",
        "description": "sterile offices, sharp suits, psychological games",
        "vector": [0.78, 0.68, 0.88, 0.08, 0.85, 0.82],
    },
    {
        "id": "cozy-cabin",
        "display_name": "Cozy cabin winter",
        "emoji": "🏔️",
        "description": "firelit interiors, snow outside, intimate warmth",
        "vector": [0.52, 0.18, 0.12, 0.65, 0.35, 0.42],
    },
    {
        "id": "foggy-european",
        "display_name": "Foggy European",
        "emoji": "🌫️",
        "description": "old cobblestones, grey skies, quiet cafes",
        "vector": [0.28, 0.20, 0.52, 0.28, 0.42, 0.18],
    },
    {
        "id": "neon-cyberpunk",
        "display_name": "Neon cyberpunk",
        "emoji": "⚡",
        "description": "electric cities, rain, future dystopia",
        "vector": [0.22, 0.88, 0.92, 0.22, 0.72, 0.92],
    },
    {
        "id": "mediterranean-sun",
        "display_name": "Mediterranean sun",
        "emoji": "☀️",
        "description": "golden coasts, slow lunches, sensory warmth",
        "vector": [0.95, 0.32, 0.48, 0.92, 0.28, 0.45],
    },
    {
        "id": "dark-gothic",
        "display_name": "Dark gothic forest",
        "emoji": "🌲",
        "description": "ancient trees, dread, beautiful isolation",
        "vector": [0.08, 0.15, 0.12, 0.15, 0.62, 0.15],
    },
    {
        "id": "80s-neon-pastel",
        "display_name": "80s neon pastel",
        "emoji": "🕹️",
        "description": "synth pop colours, arcade glow, retro energy",
        "vector": [0.55, 0.72, 0.78, 0.58, 0.68, 0.22],
    },
    {
        "id": "sparse-desert",
        "display_name": "Sparse desert",
        "emoji": "🏜️",
        "description": "vast emptiness, brutal sun, existential silence",
        "vector": [0.95, 0.15, 0.05, 0.95, 0.22, 0.45],
    },
    {
        "id": "underwater-dreamlike",
        "display_name": "Dreamlike and surreal",
        "emoji": "🌀",
        "description": "logic bends, colour saturated, hypnotic flow",
        "vector": [0.55, 0.28, 0.45, 0.52, 0.38, 0.52],
    },
    {
        "id": "gritty-realism",
        "display_name": "Gritty urban realism",
        "emoji": "🏗️",
        "description": "handheld camera, grey concrete, raw truth",
        "vector": [0.32, 0.58, 0.82, 0.25, 0.08, 0.62],
    },
    {
        "id": "lush-tropical",
        "display_name": "Lush tropical",
        "emoji": "🌴",
        "description": "deep jungle, vivid colour, primal heat",
        "vector": [0.72, 0.38, 0.15, 0.92, 0.45, 0.48],
    },
    {
        "id": "soviet-brutalist",
        "display_name": "Soviet brutalist",
        "emoji": "🧱",
        "description": "concrete towers, grey winter, existential weight",
        "vector": [0.25, 0.22, 0.75, 0.08, 0.30, 0.18],
    },
    {
        "id": "new-wave-paris",
        "display_name": "New wave Paris",
        "emoji": "🎬",
        "description": "black and white streets, cigarettes, philosophical drift",
        "vector": [0.35, 0.30, 0.72, 0.38, 0.55, 0.25],
    },
    {
        "id": "summer-nostalgia",
        "display_name": "Summer nostalgia",
        "emoji": "🌻",
        "description": "golden light, childhood, the last days of something",
        "vector": [0.90, 0.35, 0.35, 0.85, 0.55, 0.30],
    },
    {
        "id": "space-opera",
        "display_name": "Space opera",
        "emoji": "🚀",
        "description": "vast cosmos, epic music, civilisations at stake",
        "vector": [0.50, 0.85, 0.40, 0.45, 0.82, 0.95],
    },
    {
        "id": "midnight-diner",
        "display_name": "Midnight diner",
        "emoji": "🍜",
        "description": "fluorescent warmth, strangers, 2am confessions",
        "vector": [0.62, 0.28, 0.75, 0.55, 0.42, 0.75],
    },
    {
        "id": "cold-war-espionage",
        "display_name": "Cold war espionage",
        "emoji": "🕵️",
        "description": "muted palettes, paranoia, divided cities",
        "vector": [0.22, 0.55, 0.72, 0.12, 0.60, 0.15],
    },
    {
        "id": "art-house-minimalist",
        "display_name": "Art house minimalist",
        "emoji": "🎨",
        "description": "silence, negative space, every frame deliberate",
        "vector": [0.45, 0.05, 0.38, 0.42, 0.35, 0.45],
    },
    {
        "id": "high-fashion",
        "display_name": "High fashion world",
        "emoji": "✨",
        "description": "designer rooms, sharp aesthetics, beautiful people",
        "vector": [0.88, 0.55, 0.82, 0.65, 0.95, 0.85],
    },
    {
        "id": "rural-american",
        "display_name": "Rural American gothic",
        "emoji": "🌾",
        "description": "trailer parks, cornfields, dark secrets under skies",
        "vector": [0.65, 0.30, 0.10, 0.55, 0.25, 0.55],
    },
    {
        "id": "underwater-sea",
        "display_name": "Ocean deep",
        "emoji": "🌊",
        "description": "the sea as metaphor, pressure, blue vastness",
        "vector": [0.35, 0.30, 0.12, 0.40, 0.52, 0.48],
    },
    {
        "id": "war-torn",
        "display_name": "War-torn landscape",
        "emoji": "💥",
        "description": "rubble, heroism, cost, the smell of smoke",
        "vector": [0.30, 0.78, 0.55, 0.22, 0.15, 0.38],
    },
]

# ── Curated atmosphere genome tags (top 200) ──────────────────────────────────
# Used in seed_vibes.py to pick vibe_tags from MovieLens genome.

ATMOSPHERE_GENOME_TAGS = [
    "atmospheric", "slow burn", "visually stunning", "dark", "neon-lit",
    "gritty", "gripping", "suspenseful", "melancholic", "haunting",
    "dreamlike", "surreal", "minimalist", "quiet", "contemplative",
    "tense", "kinetic", "fast-paced", "frenetic", "explosive",
    "warm", "cozy", "cold", "sterile", "clinical",
    "beautiful", "gorgeous", "lush", "sweeping", "epic",
    "handheld", "documentary-style", "raw", "rough", "polished",
    "slick", "elegant", "glossy", "stylized", "noir",
    "dim", "shadowy", "overcast", "foggy", "misty",
    "sunny", "golden", "radiant", "bright", "luminous",
    "isolated", "remote", "wilderness", "rural", "forest",
    "urban", "metropolitan", "crowded", "city", "streets",
    "vintage", "retro", "nostalgic", "period piece", "historical",
    "contemporary", "modern", "futuristic", "cyberpunk", "sci-fi",
    "winter", "snow", "frozen", "wintry", "icy",
    "summer", "tropical", "hot", "sultry", "sun-drenched",
    "eerie", "ominous", "dread", "unsettling", "creepy",
    "heartwarming", "uplifting", "inspiring", "joyful", "hopeful",
    "claustrophobic", "open", "vast", "spacious", "enclosed",
    "intimate", "personal", "confessional", "immersive", "experiential",
    "action-packed", "filler", "breathless", "propulsive", "relentless",
    "meditative", "languid", "deliberate", "measured", "unhurried",
    "sensory", "tactile", "textured", "palpable", "immersive",
    "neo-noir", "western", "gothic", "baroque", "impressionistic",
    "absurdist", "existential", "philosophical", "cerebral", "intellectual",
    "visceral", "raw emotion", "gut-wrenching", "cathartic", "emotional",
    "spectacular", "massive", "grand", "intimate", "small-scale",
    "acid trip", "trippy", "hallucinatory", "fever dream", "hypnotic",
    "melancholy", "somber", "bleak", "hopeless", "nihilistic",
    "violent", "brutal", "savage", "graphic", "unflinching",
    "slow motion", "time-lapse", "montage", "non-linear", "fragmented",
    "lyrical", "poetic", "musical", "rhythmic", "pulsing",
    "claustrophobic", "breathtaking", "landscape", "architecture", "texture",
    "rainy", "stormy", "thunder", "lightning", "wind",
    "desert", "ocean", "mountain", "forest", "city",
    "night", "day", "dawn", "dusk", "midnight",
    "black and white", "monochrome", "sepia", "saturated", "muted",
    "neon", "pastel", "bold colors", "earthy tones", "cold palette",
    "warm palette", "golden hour", "blue hour", "overexposed", "underexposed",
]
